version: '3.8'

services:
  frontend:
    build:
      context: ./fts-semeso-app
    ports:
      - '3000:3000'
    volumes:
      - ./fts-semeso-app:/app
    depends_on:
      - fts-semeso-server
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./fts-semeso-server
    ports:
      - '5000:5000'
    volumes:
      - ./fts-semeso-server:/app
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
